name: Publish

on:
  push:
    tags:
      - '*'

jobs:
    Minify-CSS:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Auto Minify
              uses: nizarmah/auto-minify@v2.1.1
              with:
                output: 'minified'
            - name: Archive files
              run: zip -r -q minified.zip minified
            - name: Upload minified files to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: minified.zip
                tag: ${{ github.ref }}
                overwrite: true
